version: '3.8'
services:

  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  backend:
    image: potapovjakov/yadisk:latest
    restart: always
    depends_on:
      - db
    env_file:
      - ./.env

volumes:
  postgres_data:
